### ISSUE TITLE
Data not Forwarding to Google

### ISSUE THREAD

**Issue by jordan-tr** [mparticle-integrations/mparticle-javascript-integration-adwords#38]
Hey guys!

We are an EU based company, and we are self hosting the mParticle web sdk and are having issues in receiving data to Google. We can see that when we trigger events it's being populated in the mP interface, however they never end up in Google Ads. Could you potentially know why that would be?

Thanks!

Jordan

**Comment by rmi22186** [comment]
Hi Jordan - 

I reached out to our team and it looks like they are tracking this internally right now.  I'm going to close this issue since our technical services/customer support team is on it right now.
